name: MSYS2
on: [push, pull_request, workflow_dispatch]

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: ${{matrix.sys}}
          install: mingw-w64-${{matrix.env}}-openssl mingw-w64-${{matrix.env}}-cmake mingw-w64-${{matrix.env}}-libvterm git curl base-devel mingw-w64-${{matrix.env}}-toolchain
      - name: CI-Build
        id: build
        run: |
          echo 'Running in MSYS2!'
          cd /home/runneradmin/
          git clone https://github.com/xhcoding/emacs-libvterm
          cd emacs-libvterm
          mkdir build && cd build && cmake .. && ninja
          cp /${{matrix.sys}}/bin/libvterm-0.dll ./
          cp ../vterm-module.dll ./
      - name: "Upload DLLs"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.env}}-emacs-libvterm
          path: ${{ steps.msys2.outputs.msys2-location }}/home/runneradmin/emacs-libvterm/build/*.dll
